// One-line descriptions and official sites for every technology in lib/tech.js.
export const TECH_INFO = {
  'React': ['A JavaScript library from Meta for building user interfaces out of components.', 'https://react.dev'],
  'Next.js': ['A React framework by Vercel with server rendering, static generation and file-based routing.', 'https://nextjs.org'],
  'Vue.js': ['A progressive JavaScript framework for building user interfaces with reactive components.', 'https://vuejs.org'],
  'Nuxt': ['A full-stack framework built on Vue.js, with server rendering and file-based routing.', 'https://nuxt.com'],
  'Angular': ['A TypeScript web application framework maintained by Google.', 'https://angular.dev'],
  'AngularJS': ['The original Angular 1.x framework, now end-of-life since January 2022.', 'https://angularjs.org'],
  'Svelte': ['A component framework that compiles to small, framework-free JavaScript at build time.', 'https://svelte.dev'],
  'SvelteKit': ['The application framework for Svelte, with routing, server rendering and adapters for many hosts.', 'https://svelte.dev/docs/kit'],
  'Gatsby': ['A React-based static site generator with a GraphQL data layer.', 'https://www.gatsbyjs.com'],
  'Remix': ['A full-stack React framework focused on web standards; now merged into React Router.', 'https://remix.run'],
  'Astro': ['A content-focused web framework that ships zero JavaScript by default, using "islands" for interactivity.', 'https://astro.build'],
  'Preact': ['A 3 kB alternative to React with the same modern API.', 'https://preactjs.com'],
  'SolidJS': ['A reactive JavaScript UI library with fine-grained updates and no virtual DOM.', 'https://www.solidjs.com'],
  'Qwik': ['A framework built around resumability, so pages become interactive without hydration.', 'https://qwik.dev'],
  'Ember.js': ['A batteries-included JavaScript framework for ambitious web applications.', 'https://emberjs.com'],
  'Backbone.js': ['One of the first MVC libraries for JavaScript applications, with models, views and routers.', 'https://backbonejs.org'],
  'Alpine.js': ['A lightweight framework for adding behaviour directly in HTML markup.', 'https://alpinejs.dev'],
  'htmx': ['A library that adds AJAX, WebSockets and server-sent events to HTML through attributes.', 'https://htmx.org'],
  'jQuery': ['The classic JavaScript library for DOM manipulation, events and AJAX.', 'https://jquery.com'],
  'Lodash / Underscore': ['Utility libraries with helpers for arrays, objects, strings and functions.', 'https://lodash.com'],
  'Three.js': ['A JavaScript 3D library that renders WebGL scenes in the browser.', 'https://threejs.org'],
  'GSAP': ['The GreenSock Animation Platform, a high-performance JavaScript animation library.', 'https://gsap.com'],
  'core-js': ['A modular standard library of JavaScript polyfills, usually bundled by build tools.', 'https://github.com/zloirock/core-js'],
  'WordPress': ['The most widely used open-source content management system, written in PHP.', 'https://wordpress.org'],
  'Drupal': ['An open-source PHP content management framework used by many large organisations.', 'https://www.drupal.org'],
  'Joomla': ['An open-source PHP content management system.', 'https://www.joomla.org'],
  'Ghost': ['An open-source publishing platform for blogs, newsletters and paid memberships.', 'https://ghost.org'],
  'Wix': ['A hosted drag-and-drop website builder.', 'https://www.wix.com'],
  'Squarespace': ['A hosted website builder with templates for portfolios, blogs and online stores.', 'https://www.squarespace.com'],
  'Webflow': ['A visual website builder and CMS that produces production-ready HTML and CSS.', 'https://webflow.com'],
  'Framer': ['A design tool and website builder that publishes interactive sites.', 'https://www.framer.com'],
  'HubSpot CMS': ['HubSpot\'s hosted content management system, integrated with its marketing tools.', 'https://www.hubspot.com/products/cms'],
  'Hugo': ['A fast static site generator written in Go.', 'https://gohugo.io'],
  'Jekyll': ['A Ruby static site generator, the engine behind classic GitHub Pages sites.', 'https://jekyllrb.com'],
  'Hexo': ['A Node.js static site generator popular for blogs.', 'https://hexo.io'],
  'Docusaurus': ['A React-based static site generator for documentation, by Meta.', 'https://docusaurus.io'],
  'VitePress': ['A Vite- and Vue-powered static site generator for documentation.', 'https://vitepress.dev'],
  'MkDocs': ['A Python static site generator for project documentation written in Markdown.', 'https://www.mkdocs.org'],
  'Blogger': ['Google\'s free hosted blogging platform.', 'https://www.blogger.com'],
  'Medium': ['A hosted publishing platform; detected on sites running on Medium custom domains.', 'https://medium.com'],
  'Notion': ['Pages published from the Notion workspace app.', 'https://www.notion.com'],
  'Shopify': ['A hosted e-commerce platform for online stores and point of sale.', 'https://www.shopify.com'],
  'WooCommerce': ['The e-commerce plugin for WordPress.', 'https://woocommerce.com'],
  'Magento': ['An open-source PHP e-commerce platform, now Adobe Commerce.', 'https://business.adobe.com/products/magento/magento-commerce.html'],
  'BigCommerce': ['A hosted e-commerce platform for mid-size and large stores.', 'https://www.bigcommerce.com'],
  'PrestaShop': ['An open-source PHP e-commerce platform popular in Europe.', 'https://prestashop.com'],
  'Shopline': ['A hosted e-commerce platform popular in Asia.', 'https://shopline.com'],
  'Google Analytics': ['Google\'s web analytics service (GA4).', 'https://marketingplatform.google.com/about/analytics/'],
  'Google Tag Manager': ['Google\'s tag management system for loading analytics and marketing scripts.', 'https://tagmanager.google.com'],
  'Meta Pixel': ['Meta\'s conversion-tracking script for Facebook and Instagram advertising.', 'https://www.facebook.com/business/tools/meta-pixel'],
  'Hotjar': ['Heatmaps, session recordings and on-site surveys.', 'https://www.hotjar.com'],
  'Microsoft Clarity': ['Microsoft\'s free heatmap and session-recording analytics.', 'https://clarity.microsoft.com'],
  'Plausible': ['Lightweight, cookie-free, open-source web analytics.', 'https://plausible.io'],
  'Fathom': ['Privacy-focused, cookie-free website analytics.', 'https://usefathom.com'],
  'Umami': ['Open-source, privacy-focused web analytics.', 'https://umami.is'],
  'Matomo': ['Open-source web analytics, formerly Piwik, often self-hosted.', 'https://matomo.org'],
  'Mixpanel': ['Product analytics for tracking user events and funnels.', 'https://mixpanel.com'],
  'Segment': ['A customer data platform that routes events to analytics and marketing tools.', 'https://segment.com'],
  'Amplitude': ['Product analytics and experimentation platform.', 'https://amplitude.com'],
  'PostHog': ['Open-source product analytics, session replay and feature flags.', 'https://posthog.com'],
  'Heap': ['Product analytics that captures interactions automatically.', 'https://www.heap.io'],
  'Baidu Tongji': ['Baidu\'s web analytics service, common on Chinese websites.', 'https://tongji.baidu.com'],
  'Yandex Metrica': ['Yandex\'s free web analytics with heatmaps and session replay.', 'https://metrica.yandex.com'],
  'Vercel Analytics': ['Privacy-friendly analytics built into the Vercel hosting platform.', 'https://vercel.com/analytics'],
  'Cloudflare Web Analytics': ['Cloudflare\'s free, cookie-free website analytics.', 'https://www.cloudflare.com/web-analytics/'],
  'Google AdSense': ['Google\'s program for publishers to show ads and earn revenue.', 'https://adsense.google.com'],
  'Google Ad Manager': ['Google\'s ad server for large publishers (formerly DoubleClick for Publishers).', 'https://admanager.google.com'],
  'Amazon Ads': ['Amazon Publisher Services header bidding and display ads.', 'https://aps.amazon.com'],
  'Taboola': ['A content recommendation and native advertising network.', 'https://www.taboola.com'],
  'HubSpot': ['HubSpot\'s marketing, sales and CRM tracking and forms.', 'https://www.hubspot.com'],
  'Mailchimp': ['Email marketing and newsletter sign-up forms.', 'https://mailchimp.com'],
  'Klaviyo': ['Email and SMS marketing automation, popular with online stores.', 'https://www.klaviyo.com'],
  'Intercom': ['Customer messaging: live chat, help centre and support bots.', 'https://www.intercom.com'],
  'Crisp': ['Live chat and customer support inbox.', 'https://crisp.chat'],
  'Zendesk': ['Customer service software, including the Zendesk web widget.', 'https://www.zendesk.com'],
  'Drift': ['Conversational marketing and sales chat.', 'https://www.salesloft.com/platform/drift'],
  'tawk.to': ['Free live chat widget for websites.', 'https://www.tawk.to'],
  'Stripe': ['Online payments infrastructure; Stripe.js loads its checkout elements.', 'https://stripe.com'],
  'PayPal': ['PayPal\'s checkout buttons and JavaScript SDK.', 'https://developer.paypal.com'],
  'Paddle': ['A merchant of record for software and SaaS payments.', 'https://www.paddle.com'],
  'Lemon Squeezy': ['A merchant of record for selling digital products and subscriptions.', 'https://www.lemonsqueezy.com'],
  'reCAPTCHA': ['Google\'s bot-detection service for forms and logins.', 'https://developers.google.com/recaptcha'],
  'hCaptcha': ['A privacy-focused CAPTCHA and bot-detection service.', 'https://www.hcaptcha.com'],
  'Cloudflare Turnstile': ['Cloudflare\'s CAPTCHA alternative that verifies visitors without puzzles.', 'https://www.cloudflare.com/products/turnstile/'],
  'Sucuri': ['A website firewall and malware-protection service.', 'https://sucuri.net'],
  'Bootstrap': ['The popular CSS framework for responsive, mobile-first sites.', 'https://getbootstrap.com'],
  'Tailwind CSS': ['A utility-first CSS framework.', 'https://tailwindcss.com'],
  'Font Awesome': ['An icon font and SVG icon toolkit.', 'https://fontawesome.com'],
  'Google Fonts': ['Google\'s free library of web fonts.', 'https://fonts.google.com'],
  'Adobe Fonts': ['Adobe\'s web-font service, formerly Typekit.', 'https://fonts.adobe.com'],
  'Material UI': ['React components implementing Google\'s Material Design.', 'https://mui.com'],
  'Ant Design': ['An enterprise-class React UI design system from Ant Group.', 'https://ant.design'],
  'Element Plus': ['A Vue 3 UI component library.', 'https://element-plus.org'],
  'Cloudflare': ['CDN, DNS, DDoS protection and security services in front of a website.', 'https://www.cloudflare.com'],
  'Fastly': ['An edge cloud platform and CDN.', 'https://www.fastly.com'],
  'Amazon CloudFront': ['Amazon Web Services\' content delivery network.', 'https://aws.amazon.com/cloudfront/'],
  'Akamai': ['One of the largest CDN and edge security providers.', 'https://www.akamai.com'],
  'Azure Front Door': ['Microsoft Azure\'s global CDN and application delivery service.', 'https://azure.microsoft.com/products/frontdoor/'],
  'Alibaba Cloud CDN': ['Alibaba Cloud\'s content delivery network, widely used in China.', 'https://www.alibabacloud.com/product/content-delivery-network'],
  'jsDelivr': ['A free public CDN for open-source npm and GitHub files.', 'https://www.jsdelivr.com'],
  'cdnjs': ['A free public CDN for JavaScript and CSS libraries, run by Cloudflare.', 'https://cdnjs.com'],
  'unpkg': ['A free CDN that serves files from npm packages.', 'https://unpkg.com'],
  'Vercel': ['A cloud platform for frontend frameworks and static sites.', 'https://vercel.com'],
  'Netlify': ['A platform for deploying static sites and serverless functions.', 'https://www.netlify.com'],
  'GitHub Pages': ['Free static site hosting from GitHub repositories.', 'https://pages.github.com'],
  'Render': ['A cloud platform for web services, static sites and databases.', 'https://render.com'],
  'Fly.io': ['A platform that runs application containers close to users worldwide.', 'https://fly.io'],
  'Railway': ['A deployment platform for apps and databases.', 'https://railway.com'],
  'Deno Deploy': ['A serverless edge platform for JavaScript and TypeScript.', 'https://deno.com/deploy'],
  'Kinsta': ['Managed WordPress and application hosting.', 'https://kinsta.com'],
  'WP Engine': ['Managed WordPress hosting.', 'https://wpengine.com'],
  'Pantheon': ['A hosting platform for Drupal and WordPress sites.', 'https://pantheon.io'],
  'Google Cloud Storage': ['Static files served directly from Google Cloud Storage buckets.', 'https://cloud.google.com/storage'],
  'Nginx': ['A high-performance web server, reverse proxy and load balancer.', 'https://nginx.org'],
  'Apache': ['The Apache HTTP Server, one of the oldest open-source web servers.', 'https://httpd.apache.org'],
  'LiteSpeed': ['A high-performance web server, a drop-in replacement for Apache.', 'https://www.litespeedtech.com'],
  'Microsoft IIS': ['Microsoft\'s Internet Information Services web server for Windows.', 'https://www.iis.net'],
  'OpenResty': ['A web platform that extends Nginx with LuaJIT scripting.', 'https://openresty.org'],
  'Caddy': ['A web server with automatic HTTPS, written in Go.', 'https://caddyserver.com'],
  'Envoy': ['A cloud-native edge and service proxy.', 'https://www.envoyproxy.io'],
  'Varnish': ['An HTTP caching reverse proxy.', 'https://varnish-cache.org'],
  'PHP': ['A server-side scripting language, revealed by the X-Powered-By header.', 'https://www.php.net'],
  'ASP.NET': ['Microsoft\'s server-side web framework for .NET.', 'https://dotnet.microsoft.com/apps/aspnet'],
  'Express': ['A minimal web framework for Node.js.', 'https://expressjs.com'],
  'Next.js server': ['A Next.js server announcing itself in the X-Powered-By header.', 'https://nextjs.org'],
};

export const CATEGORY_LABEL = {
  framework: 'JavaScript frameworks',
  library: 'JavaScript libraries',
  cms: 'CMS & site builders',
  ecommerce: 'E-commerce platforms',
  ui: 'UI frameworks & fonts',
  analytics: 'Analytics',
  ads: 'Advertising',
  marketing: 'Marketing',
  chat: 'Live chat & support',
  payments: 'Payments',
  security: 'Security',
  cdn: 'CDN',
  hosting: 'Hosting',
  server: 'Web servers',
  backend: 'Back-end',
};

export const slugify = (name) => name.toLowerCase().replace(/\+/g, 'plus').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
